.catalog:
  version: 2
  upgrade_from: 2
  questions:
    - variable: SITE_DNAME
      description: Specify the domain name of the site.
      label: Site domain name
      required: true
      default: projectname.portal.siemonster.com
      type: string
    - variable: BRANCH_NAME
      description: Specify the branch name to checkout.
      label: Branch name
      required: true
      default: master
      type: string
    - variable: ACCESS_TOKEN
      description: Specify the access token.
      label: Access Token
      required: true
      default: Enter Token here
      type: string
    - variable: ELASTICSEARCH_KRAKEN_TIAMAT_HEAP_SIZE
      label: ELASTICSEARCH_KRAKEN_TIAMAT_HEAP_SIZE
      required: true
      default: 2g
      type: string
    - variable: ELASTICSEARCH_PROTEUS_CAPRICORN_HEAP_SIZE
      label: ELASTICSEARCH_PROTEUS_CAPRICORN_HEAP_SIZE
      required: true
      default: 1g
      type: string
    - variable: MYSQL_DATABASE
      label: MYSQL_DATABASE
      description: MySQL DB for 411
      type: string
      required: true
      default: fouroneone
    - variable: MYSQL_USER
      label: MYSQL_USER
      description: MySQL User for 411
      type: string
      required: true
      default: fouroneone
    - variable: MYSQL_PASS
      label: MYSQL_PASS
      description: MySQL Password for 411
      type: password
      required: true
      type: password
      default: siemonster
    - variable: MYSQL_ROOT_PASSWORD
      label: MYSQL_ROOT_PASSWORD
      description: MySQL Root Password
      type: password
      required: true
      default: siemonster
    - variable: SITE_ID
      label: SITE_ID
      description: SITE_ID for 411
      type: int
      required: true
      default: 1    
    - variable: GMAILRELAY_EMAIL
      label: GMAILRELAY_EMAIL
      description: enter Gmail Relay e-mail address.
      required: false
      type: string
    - variable: GMAILRELAY_EMAILPASS
      label: GMAILRELAY_EMAILPASS
      description: enter password for e-mail address.
      required: false
      type: string

siemonster:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000

msa:
  scale: 1
  retain_ip: true

msa-volume:
  scale: 1
  retain_ip: true

heaven-backend:
  scale: 1
  retain_ip: true


